ConvE:
  embedding_dim: 200
  input_drop: 0.2
  hidden_drop: 0.3
  feat_drop: 0.2
  embedding_shape1: 20
  use_bias: False
  kernel_size: (3, 3)
  filter_channels: 32
  stride: 1
  padding: 0
  load_path: '/home/scratch/gis/saved_models/conve_pretrained/FB15k-237_conve_0.2_0.3.model'
DistMult:
  embedding_dim: 300
  input_drop: 0.04