data_dir: '/Volumes/External HDD/dataset/tacred/data/json'
vocab_dir: '/Volumes/External HDD/dataset/tacred/data/vocab'
test_save_dir: '/Volumes/External HDD/dataset/tacred/test_perfs'
save_dir: '/Volumes/External HDD/dataset/tacred/saved_models'
encoding_type: 'BiLSTM' # sentence encoding type: LSTM or BiLSTM
emb_dim: 300  # Word embedding dimension.
ner_dim: 30 # NER embedding dimension.
pos_dim: 30 # POS embedding dimension.
hidden_dim: 300 # RNN hidden state size.
num_layers: 2 # Num of RNN layers.
dropout: .5 # Input and RNN dropout rate.
word_dropout: .04 # The rate at which randomly set a word to UNK.
topn: 1e10  # Only finetune top N embeddings.
lower: False  # Lowercase all words.
lr: 1.0 # Applies to SGD and Adagrad
lr_decay: 0.9
optim: 'sgd'  # sgd, adagrad, adam or adamax.
num_epoch: 30 # number of epochs
batch_size: 50
max_grad_norm: 5.0  # Gradient Clipping.
log_step: 1  # Print log every k steps.
log:  'logs.txt'  # Write training log to file.
save_epoch: 5 # Save model checkpoints every k epochs
id: 'component-wise_fact_checking'  # Model ID under which to save models.
info: ''  # Optional info for the experiment.
seed: 1234  # random seed
remove_entity_types: False # Replace subject and object granular typing with universal subject and object
cuda: True
cpu: True # Ignore CUDA.
attn: False # Use attention layer.
attn_dim: 200 # Attention size.
pe_dim: 30  # Position encoding dimension.
fact_checking_attn: True  # Whether to apply link prediction fact checking attention.
fact_checking_model: 'ConvE'
reg_params: 'fact_checking'